from pathlib import Path

# Set project dir
PROJECT_DIR = Path(__file__).parent.parent.parent.resolve()

# Set the path-to-files
TRAIN_FILE = PROJECT_DIR / "data" / "processed" / "idn" / "train.pkl"
TEST_FILE = PROJECT_DIR / "data" / "processed" / "idn" / "test.pkl"

SUB_DIR = PROJECT_DIR / "reports" / "deepfm_output"
FIG_DIR = PROJECT_DIR / "reports" / "figures"

NUM_SPLITS = 3
RANDOM_SEED = 2017

# types of columns of the dataset dataframe
CATEGORICAL_COLS = [
    # 'ps_ind_02_cat', 'ps_ind_04_cat', 'ps_ind_05_cat',
    # 'ps_car_01_cat', 'ps_car_02_cat', 'ps_car_03_cat',
    # 'ps_car_04_cat', 'ps_car_05_cat', 'ps_car_06_cat',
    # 'ps_car_07_cat', 'ps_car_08_cat', 'ps_car_09_cat',
    # 'ps_car_10_cat', 'ps_car_11_cat',
#]


    # # binary
	'geo_province__Bangka Belitung',
	'geo_province__Banten',
	'geo_province__Bengkulu',
	'geo_province__Central Java',
	'geo_province__Central Kalimantan',
	'geo_province__Central Sulawesi',
	'geo_province__DI Yogyakarta',
	'geo_province__DKI Jakarta',
	'geo_province__East Java',
	'geo_province__East Kalimantan',
	'geo_province__East Nusa Tenggara',
	'geo_province__Gorontalo',
	'geo_province__Jambi',
	'geo_province__Lampung',
	'geo_province__Maluku',
	'geo_province__Nanggroe Aceh Darussalam',
	'geo_province__North Maluku',
	'geo_province__North Sulawesi',
	'geo_province__North Sumatera',
	'geo_province__Papua',
	'geo_province__Riau',
	'geo_province__Riau Island',
	'geo_province__South Kalimantan',
	'geo_province__South Sulawesi',
	'geo_province__South Sumatera',
	'geo_province__Southeast Sulawesi',
	'geo_province__West Irian Jaya',
	'geo_province__West Java',
	'geo_province__West Kalimantan',
	'geo_province__West Nusa Tenggara',
	'geo_province__West Sulawesi',
	'geo_province__West Sumatera',
	'geo_urbrur__Urban',
	'hld_helpers__Yes',
	'hld_building__Residential building',
	'hld_occstat__Free lease, owned by other people',
	'hld_occstat__Free lease, owned by parents/family',
	'hld_occstat__Lease',
	'hld_occstat__Other',
	'hld_occstat__Owned',
	'hld_occstat__Rent',
	'hld_landstat__Freehold title (HM)',
	'hld_landstat__Not applicable',
	'hld_landstat__Other',
	'hld_landstat__Right to use title (HP)',
	'hld_roof__Concrete',
	'hld_roof__Fiber/palm',
	'hld_roof__Iron sheet',
	'hld_roof__Other',
	'hld_roof__Roof tile',
	'hld_roof__Shingle',
	'hld_wall__Concrete',
	'hld_wall__Other',
	'hld_wall__Wood',
	'hld_floor__Marble/ceramics/granite',
	'hld_floor__Other',
	'hld_floor__Soil',
	'hld_floor__Terrazzo/tiles',
	'hld_floor__Wood',
	'hld_dwater__Other',
	'hld_dwater__Pipe with meter',
	'hld_dwater__Pipe, retail payment',
	'hld_dwater__Protected spring',
	'hld_dwater__Protected/covered well',
	'hld_dwater__Rainwater',
	'hld_dwater__Recycled bottled water',
	'hld_dwater__River',
	'hld_dwater__Terrestrial well/pump',
	'hld_dwater__Unprotected spring',
	'hld_dwater__Unprotected/uncovered well',
	'hld_dwatershr__None',
	'hld_dwatershr__Not applicable',
	'hld_dwatershr__Personal',
	'hld_dwatershr__Public',
	'hld_dwateracq__Customer-based',
	'hld_dwateracq__Not buying',
	'hld_bwwater__Other',
	'hld_bwwater__Pipe with meter',
	'hld_bwwater__Pipe, retail payment',
	'hld_bwwater__Protected spring',
	'hld_bwwater__Protected/covered well',
	'hld_bwwater__Rainwater',
	'hld_bwwater__Recycled bottled water',
	'hld_bwwater__River',
	'hld_bwwater__Terrestrial well/pump',
	'hld_bwwater__Unprotected spring',
	'hld_bwwater__Unprotected/uncovered well',
	'hld_toiletshr__None',
	'hld_toiletshr__Personal',
	'hld_toiletshr__Public',
	'hld_toilet__None',
	'hld_toilet__Pit toilet/plengsengan',
	'hld_toilet__Squat toilet/cemplung',
	'hld_disposal__Other',
	'hld_disposal__Pit hole',
	'hld_disposal__Pool/field',
	'hld_disposal__River/lake/sea',
	'hld_disposal__Tank/septic tank',
	'hld_lighting__Oil lamp/torch',
	'hld_lighting__Other',
	'hld_lighting__PLN electricity',
	'hld_lighting__Paraffin lamp/petromak',
	'hld_cooking__Charcoal',
	'hld_cooking__City gas',
	'hld_cooking__Electricity',
	'hld_cooking__Firewood',
	'hld_cooking__Gas/LPG',
	'hld_cooking__Kerosene',
	'hld_cooking__Other',
	'hld_bicycle__Yes',
	'hld_motorcycle__Yes',
	'hld_boat__Yes',
	'hld_cabletv__Yes',
	'hld_aircon__Yes',
	'hld_waterheat__Yes',
	'hld_gascont__Yes',
	'hld_refrigerator__Yes',
	'hld_motorboat__Yes',
	'hld_car__Yes',
	'hld_incomeok__Yes',
	'hld_cope1__Yes',
	'hld_cope2__Yes',
	'hld_cope3__Yes',
	'hld_cope4__Yes',
	'hld_cope5__Yes',
	'hld_cope6__Yes',
	'hld_cope7__Yes',
	'hld_cope8__Yes',
	'hld_anyphone__Yes',
	'hld_anycell__Yes',
	'hld_computer__Yes',
	'cons_002__Yes',
	'cons_003__Yes',
	'cons_004__Yes',
	'cons_005__Yes',
	'cons_006__Yes',
	'cons_007__Yes',
	'cons_008__Yes',
	'cons_009__Yes',
	'cons_011__Yes',
	'cons_012__Yes',
	'cons_013__Yes',
	'cons_014__Yes',
	'cons_015__Yes',
	'cons_016__Yes',
	'cons_017__Yes',
	'cons_018__Yes',
	'cons_019__Yes',
	'cons_021__Yes',
	'cons_022__Yes',
	'cons_023__Yes',
	'cons_024__Yes',
	'cons_025__Yes',
	'cons_026__Yes',
	'cons_027__Yes',
	'cons_028__Yes',
	'cons_029__Yes',
	'cons_030__Yes',
	'cons_031__Yes',
	'cons_032__Yes',
	'cons_033__Yes',
	'cons_034__Yes',
	'cons_035__Yes',
	'cons_036__Yes',
	'cons_037__Yes',
	'cons_038__Yes',
	'cons_039__Yes',
	'cons_040__Yes',
	'cons_041__Yes',
	'cons_042__Yes',
	'cons_043__Yes',
	'cons_044__Yes',
	'cons_045__Yes',
	'cons_046__Yes',
	'cons_047__Yes',
	'cons_048__Yes',
	'cons_049__Yes',
	'cons_050__Yes',
	'cons_051__Yes',
	'cons_052__Yes',
	'cons_054__Yes',
	'cons_055__Yes',
	'cons_056__Yes',
	'cons_057__Yes',
	'cons_058__Yes',
	'cons_059__Yes',
	'cons_060__Yes',
	'cons_061__Yes',
	'cons_062__Yes',
	'cons_063__Yes',
	'cons_064__Yes',
	'cons_065__Yes',
	'cons_066__Yes',
	'cons_067__Yes',
	'cons_068__Yes',
	'cons_069__Yes',
	'cons_070__Yes',
	'cons_072__Yes',
	'cons_073__Yes',
	'cons_074__Yes',
	'cons_075__Yes',
	'cons_076__Yes',
	'cons_077__Yes',
	'cons_078__Yes',
	'cons_079__Yes',
	'cons_080__Yes',
	'cons_081__Yes',
	'cons_082__Yes',
	'cons_083__Yes',
	'cons_084__Yes',
	'cons_086__Yes',
	'cons_087__Yes',
	'cons_088__Yes',
	'cons_089__Yes',
	'cons_090__Yes',
	'cons_091__Yes',
	'cons_092__Yes',
	'cons_093__Yes',
	'cons_094__Yes',
	'cons_095__Yes',
	'cons_096__Yes',
	'cons_097__Yes',
	'cons_098__Yes',
	'cons_099__Yes',
	'cons_100__Yes',
	'cons_101__Yes',
	'cons_102__Yes',
	'cons_103__Yes',
	'cons_104__Yes',
	'cons_105__Yes',
	'cons_106__Yes',
	'cons_107__Yes',
	'cons_108__Yes',
	'cons_109__Yes',
	'cons_110__Yes',
	'cons_111__Yes',
	'cons_112__Yes',
	'cons_113__Yes',
	'cons_114__Yes',
	'cons_116__Yes',
	'cons_117__Yes',
	'cons_118__Yes',
	'cons_119__Yes',
	'cons_120__Yes',
	'cons_121__Yes',
	'cons_122__Yes',
	'cons_123__Yes',
	'cons_124__Yes',
	'cons_125__Yes',
	'cons_126__Yes',
	'cons_128__Yes',
	'cons_129__Yes',
	'cons_130__Yes',
	'cons_131__Yes',
	'cons_132__Yes',
	'cons_133__Yes',
	'cons_134__Yes',
	'cons_135__Yes',
	'cons_136__Yes',
	'cons_137__Yes',
	'cons_138__Yes',
	'cons_139__Yes',
	'cons_140__Yes',
	'cons_141__Yes',
	'cons_142__Yes',
	'cons_143__Yes',
	'cons_144__Yes',
	'cons_145__Yes',
	'cons_146__Yes',
	'cons_147__Yes',
	'cons_148__Yes',
	'cons_149__Yes',
	'cons_150__Yes',
	'cons_152__Yes',
	'cons_153__Yes',
	'cons_154__Yes',
	'cons_155__Yes',
	'cons_156__Yes',
	'cons_157__Yes',
	'cons_159__Yes',
	'cons_160__Yes',
	'cons_161__Yes',
	'cons_162__Yes',
	'cons_163__Yes',
	'cons_164__Yes',
	'cons_165__Yes',
	'cons_166__Yes',
	'cons_168__Yes',
	'cons_169__Yes',
	'cons_170__Yes',
	'cons_171__Yes',
	'cons_172__Yes',
	'cons_173__Yes',
	'cons_174__Yes',
	'cons_175__Yes',
	'cons_176__Yes',
	'cons_177__Yes',
	'cons_178__Yes',
	'cons_179__Yes',
	'cons_180__Yes',
	'cons_182__Yes',
	'cons_183__Yes',
	'cons_184__Yes',
	'cons_185__Yes',
	'cons_186__Yes',
	'cons_187__Yes',
	'cons_188__Yes',
	'cons_189__Yes',
	'cons_190__Yes',
	'cons_192__Yes',
	'cons_193__Yes',
	'cons_194__Yes',
	'cons_195__Yes',
	'cons_196__Yes',
	'cons_197__Yes',
	'cons_198__Yes',
	'cons_199__Yes',
	'cons_200__Yes',
	'cons_201__Yes',
	'cons_202__Yes',
	'cons_203__Yes',
	'cons_204__Yes',
	'cons_205__Yes',
	'cons_206__Yes',
	'cons_207__Yes',
	'cons_208__Yes',
	'cons_209__Yes',
	'cons_210__Yes',
	'cons_211__Yes',
	'cons_212__Yes',
	'cons_213__Yes',
	'cons_214__Yes',
	'cons_215__Yes',
	'cons_216__Yes',
	'cons_217__Yes',
	'cons_218__Yes',
	'cons_219__Yes',
	'cons_220__Yes',
	'cons_221__Yes',
	'cons_222__Yes',
	'cons_224__Yes',
	'cons_225__Yes',
	'cons_226__Yes',
	'cons_227__Yes',
	'cons_228__Yes',
	'cons_229__Yes',
	'cons_232__Yes',
	'cons_233__Yes',
	'cons_234__Yes',
	'cons_235__Yes',
	'cons_236__Yes',
	'cons_238__Yes',
	'cons_240__Yes',
	'cons_242__Yes',
	'cons_244__Yes',
	'cons_246__Yes',
	'cons_248__Yes',
	'cons_250__Yes',
	'cons_251__Yes',
	'cons_253__Yes',
	'cons_254__Yes',
	'cons_255__Yes',
	'cons_256__Yes',
	'cons_257__Yes',
	'cons_258__Yes',
	'cons_259__Yes',
	'cons_260__Yes',
	'cons_262__Yes',
	'cons_263__Yes',
	'cons_264__Yes',
	'cons_265__Yes',
	'cons_266__Yes',
	'cons_267__Yes',
	'cons_268__Yes',
	'cons_269__Yes',
	'cons_270__Yes',
	'cons_271__Yes',
	'cons_272__Yes',
	'cons_273__Yes',
	'cons_274__Yes',
	'cons_275__Yes',
	'cons_276__Yes',
	'cons_277__Yes',
	'cons_278__Yes',
	'cons_279__Yes',
	'cons_280__Yes',
	'cons_281__Yes',
	'cons_282__Yes',
	'cons_283__Yes',
	'cons_284__Yes',
	'cons_285__Yes',
	'cons_286__Yes',
	'cons_287__Yes',
	'cons_288__Yes',
	'cons_289__Yes',
	'cons_290__Yes',
	'cons_292__Yes',
	'cons_294__Yes',
	'cons_296__Yes',
	'cons_297__Yes',
	'cons_298__Yes',
	'cons_299__Yes',
	'cons_300__Yes',
	'cons_301__Yes',
	'cons_302__Yes',
	'cons_304__Yes',
	'cons_305__Yes',
	'cons_306__Yes',
	'cons_307__Yes',
	'cons_308__Yes',
	'cons_309__Yes',
	'cons_310__Yes',
	'cons_311__Yes',
	'cons_313__Yes',
	'cons_314__Yes',
	'cons_315__Yes',
	'cons_316__Yes',
	'cons_317__Yes',
	'cons_318__Yes',
	'cons_319__Yes',
	'cons_320__Yes',
	'cons_321__Yes',
	'cons_322__Yes',
	'cons_323__Yes',
	'cons_324__Yes',
	'cons_325__Yes',
	'cons_326__Yes',
	'cons_327__Yes',
	'cons_328__Yes',
	'cons_329__Yes',
	'cons_331__Yes',
	'cons_332__Yes',
	'cons_333__Yes',
	'cons_334__Yes',
	'cons_335__Yes',
	'cons_336__Yes',
	'cons_338__Yes',
	'cons_339__Yes',
	'cons_340__Yes',
	'cons_341__Yes',
	'cons_342__Yes',
	'cons_343__Yes',    
]
    
NUMERIC_COLS = [    
    # numeric
	'geo_district',
	'geo_subdistrict',
	'geo_village',
	'der_hhsize',
	'hld_nbcell',
	'der_nchild10under',
	'der_nmalesover10',
	'der_nfemalesover10',
	'der_nliterate',
	'der_nemployedpast3mo',
	'der_ninternetpast3mo'

    # feature engineering
    # "missing_feat", "ps_car_13_x_ps_reg_03",
]

IGNORE_COLS = [
    "id", "target",
#    "ps_calc_01", "ps_calc_02", "ps_calc_03", "ps_calc_04",
#    "ps_calc_05", "ps_calc_06", "ps_calc_07", "ps_calc_08",
#    "ps_calc_09", "ps_calc_10", "ps_calc_11", "ps_calc_12",
#    "ps_calc_13", "ps_calc_14",
#    "ps_calc_15_bin", "ps_calc_16_bin", "ps_calc_17_bin",
#    "ps_calc_18_bin", "ps_calc_19_bin", "ps_calc_20_bin"
]
